/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.NGOAdminRole;

import code.EcoSystem;
import code.Enterprise.Enterprise;
import code.Networks.Networks;
import code.Org.OrgNGOAdmin;
import code.Org.Organization;
import code.SystemUserAccount.SystemUsers;
import code.ProcessQueue.FDAApprovalRequest;
import code.ProcessQueue.NgoDonorReq;
import code.ProcessQueue.NGOFundRequest;
import code.ProcessQueue.ProcessRequest;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import userinterface.FoodInspectorRole.MapJPanel;
import userinterface.FoodInspectorRole.InspectorWorkRequestJPanel;

/**
 *
 * @author shruti
 */
public class NGOAdminWorkAreaPanel extends javax.swing.JPanel {

    private JPanel usrCnter;
    private SystemUsers usrAcc;
    private EcoSystem ecoSys;
    private Enterprise ent;
    private OrgNGOAdmin ngoAdmOrg;

    /**
     * Creates new form NGOAdministratorWorkAreaPanel
     */
    public NGOAdminWorkAreaPanel(JPanel userProcessContainer, SystemUsers userAccount, Organization organization, Enterprise enterprise) {
        initComponents();
        this.usrCnter = userProcessContainer;
        this.ngoAdmOrg = (OrgNGOAdmin) organization;
        this.usrAcc = userAccount;
        this.ent = enterprise;
        populateRequestTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblNgoAdmWrkArea = new javax.swing.JTable();
        AssignToMeButton = new javax.swing.JButton();
        processRequest = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        mapButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        img = new javax.swing.JLabel();

        setBackground(new java.awt.Color(253, 249, 232));

        tblNgoAdmWrkArea.setBackground(new java.awt.Color(204, 204, 204));
        tblNgoAdmWrkArea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Location", "Sender", "Receiver", "Status", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblNgoAdmWrkArea);

        AssignToMeButton.setBackground(new java.awt.Color(204, 130, 43));
        AssignToMeButton.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        AssignToMeButton.setText("Assign To Me");
        AssignToMeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignToMeButtonActionPerformed(evt);
            }
        });

        processRequest.setBackground(new java.awt.Color(204, 130, 43));
        processRequest.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        processRequest.setText("Process Request");
        processRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processRequestActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("YuGothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 130, 43));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NGO Admin Panel");

        mapButton.setBackground(new java.awt.Color(204, 130, 43));
        mapButton.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        mapButton.setText("Verification on Map");
        mapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapButtonActionPerformed(evt);
            }
        });

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clipart3038906.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(398, 398, 398))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 123, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(img)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(AssignToMeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(83, 83, 83)
                                            .addComponent(processRequest))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(mapButton)
                                            .addGap(106, 106, 106))))
                                .addGap(452, 452, 452)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(797, 797, 797))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(processRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AssignToMeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(mapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(img)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AssignToMeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignToMeButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblNgoAdmWrkArea.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row first from the table to view details");
            return;
        } else {
            ProcessRequest request = (NGOFundRequest) tblNgoAdmWrkArea.getValueAt(selectedRow, 0);
            if (request.getProcessStatus().equals("Sent")) {
                request.setRcvr(usrAcc);
                request.setProcessStatus("Pending on " + request.getRcvr().getEmploye().getEmpName());
                populateRequestTable();
                JOptionPane.showMessageDialog(null, "Success !! Request is assigned to you ");
            } else {
                JOptionPane.showMessageDialog(null, "Can't assign this work request, as the work request is in " + request.getProcessStatus() + " status", "Warning!", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_AssignToMeButtonActionPerformed

    private void processRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processRequestActionPerformed
        
     // TODO add your handling code here:
        int selectedRow = tblNgoAdmWrkArea.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row first from the table to view details");
            return;
        } else {

            NGOFundRequest request = (NGOFundRequest) tblNgoAdmWrkArea.getValueAt(selectedRow, 0);

            if (request.getProcessStatus().equals("Rejected")) {
                JOptionPane.showMessageDialog(null, "Cannot process a Rejected Request", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (request.getProcessStatus().equalsIgnoreCase("Sent to Director")) {
                JOptionPane.showMessageDialog(null, "Request already processed", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (request.getProcessStatus().equalsIgnoreCase("Sent")) {
                JOptionPane.showMessageDialog(null, "Assign the request first");
                return;
            }
            if (!usrAcc.equals(request.getRcvr())) {
                JOptionPane.showMessageDialog(null, "Not Authorized", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (!usrAcc.getEmploye().equals(request.getRcvr().getEmploye())) {
                JOptionPane.showMessageDialog(null, "Request assigned to other Officer", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            } else {

                NGOAdminWorkRequestJPanel panel = new NGOAdminWorkRequestJPanel(usrCnter, usrAcc, request, ent);
                usrCnter.add("OfficerProcessWorkRequestJPanel", panel);
                CardLayout layout = (CardLayout) usrCnter.getLayout();
                layout.next(usrCnter);

            }
    }
    }//GEN-LAST:event_processRequestActionPerformed

    private void mapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapButtonActionPerformed
        // TODO add your handling code here:
        MapJPanel mapJPanel = new MapJPanel(usrCnter);
        usrCnter.add("mapJPanel",mapJPanel);
        CardLayout layout=(CardLayout)usrCnter.getLayout();
        layout.next(usrCnter);
    }//GEN-LAST:event_mapButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssignToMeButton;
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mapButton;
    private javax.swing.JButton processRequest;
    private javax.swing.JTable tblNgoAdmWrkArea;
    // End of variables declaration//GEN-END:variables

    void populateRequestTable() {
         DefaultTableModel model = (DefaultTableModel) tblNgoAdmWrkArea.getModel();

        model.setRowCount(0);

        for (ProcessRequest request : ngoAdmOrg.getProcessQueue().getProcesReq()) {
            Object[] row = new Object[5];
            String status = request.getProcessStatus();
            row[0] = ((NGOFundRequest) request);
            row[1] = request.getSndr().getEmploye().getEmpName();
            if (status.equalsIgnoreCase("Sent to Director") ) {
                row[2] = null;
            } else {
                row[2] = request.getRcvr() == null ? null : request.getRcvr().getEmploye().getEmpName();
            }
            row[3] = request.getProcessStatus();
            row[4] = ((NGOFundRequest) request).getAmountRequired();

            model.addRow(row);
        }
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tblNgoAdmWrkArea.setRowSorter(sorter);
    }
}
