/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.VolunteerRole;

import code.Enterprise.Enterprise;
import code.Org.OrderProcess;
import code.Org.Organization;
import code.SystemUserAccount.SystemUsers;
import code.ProcessQueue.OrderPlaceRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shruti
 */
public class RequestHotelFoodJPanel extends javax.swing.JPanel {

    private JPanel jPanel;
    private Enterprise entrpz;
    private SystemUsers usrAcnt;
    private OrderPlaceRequest pntTrmntWrReq;

    /**
     * Creates new form RequestLabTestJPanel
     */
    public RequestHotelFoodJPanel(JPanel userProcessContainer, SystemUsers account, Enterprise enterprise, OrderPlaceRequest patientTreatmentWorkRequest) {
        initComponents();

        this.jPanel = userProcessContainer;
        this.entrpz = enterprise;
        this.usrAcnt = account;
        this.pntTrmntWrReq = patientTreatmentWorkRequest;
        lblValue.setText(enterprise.getName());
        btnReqTst.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReqTst = new javax.swing.JButton();
        lblMsg = new javax.swing.JLabel();
        txtMsg = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblValue = new javax.swing.JLabel();
        lblEnt = new javax.swing.JLabel();
        lblLabTyp = new javax.swing.JLabel();
        txtLabTyp = new javax.swing.JTextField();
        lblLabTypReq = new javax.swing.JLabel();
        imgLabTstReq = new javax.swing.JLabel();

        setBackground(new java.awt.Color(253, 249, 232));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReqTst.setBackground(new java.awt.Color(204, 130, 43));
        btnReqTst.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnReqTst.setForeground(new java.awt.Color(255, 255, 255));
        btnReqTst.setText("Request Storage");
        btnReqTst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReqTstActionPerformed(evt);
            }
        });
        add(btnReqTst, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 170, 30));

        lblMsg.setBackground(new java.awt.Color(204, 130, 43));
        lblMsg.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblMsg.setForeground(new java.awt.Color(204, 130, 43));
        lblMsg.setText("Message:");
        add(lblMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 70, -1));
        add(txtMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 130, 30));

        btnBack.setBackground(new java.awt.Color(204, 130, 43));
        btnBack.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 30));

        lblValue.setBackground(new java.awt.Color(204, 130, 43));
        lblValue.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblValue.setForeground(new java.awt.Color(204, 130, 43));
        lblValue.setText("<value>");
        add(lblValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 130, 20));

        lblEnt.setBackground(new java.awt.Color(204, 130, 43));
        lblEnt.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblEnt.setForeground(new java.awt.Color(204, 130, 43));
        lblEnt.setText("Enterprise :");
        add(lblEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 90, 20));

        lblLabTyp.setBackground(new java.awt.Color(204, 130, 43));
        lblLabTyp.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblLabTyp.setForeground(new java.awt.Color(204, 130, 43));
        lblLabTyp.setText("Food Type");
        add(lblLabTyp, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, -1, -1));
        add(txtLabTyp, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 130, 30));

        lblLabTypReq.setBackground(new java.awt.Color(204, 130, 43));
        lblLabTypReq.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lblLabTypReq.setForeground(new java.awt.Color(204, 130, 43));
        lblLabTypReq.setText("Food from storage Request");
        add(lblLabTypReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        imgLabTstReq.setForeground(new java.awt.Color(204, 130, 43));
        imgLabTstReq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/orderProcessinggifff.gif"))); // NOI18N
        imgLabTstReq.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(imgLabTstReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 810));
    }// </editor-fold>//GEN-END:initComponents

    private void btnReqTstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReqTstActionPerformed

        String labType = txtLabTyp.getText().trim();
        String message = txtMsg.getText().trim();

        if (labType.equals("")) {
            JOptionPane.showMessageDialog(null, "Food type is mandatory!");
            return;
        }
        if (message.equals("")) {
            JOptionPane.showMessageDialog(null, "Message is mandatory");
            return;
        }


        pntTrmntWrReq.setOrderStatus(message);
        pntTrmntWrReq.setSndr(usrAcnt);
        pntTrmntWrReq.setProcessStatus("SentToStorage");
        pntTrmntWrReq.setRcvr(null);

        Organization org = null;
        for (Organization organization : entrpz.getOrgDir().getOrganizations()) {

            if (organization instanceof OrderProcess) {
                org = organization;
                break;
            }
        }
        if (org != null) {

            org.getProcessQueue().getProcesReq().add(pntTrmntWrReq);
            usrAcnt.getProcessQueue().getProcesReq().add(pntTrmntWrReq);

            JOptionPane.showMessageDialog(null, "Process request sent");
            txtMsg.setText("");
            txtLabTyp.setText("");
            btnReqTst.setEnabled(false);
        }

    }//GEN-LAST:event_btnReqTstActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        jPanel.remove(this);
        Component[] componentArray = jPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        VolunteerWorkAreaJPanel dwjp = (VolunteerWorkAreaJPanel) component;
        dwjp.pplReqTbl();
        CardLayout layout = (CardLayout) jPanel.getLayout();
        layout.previous(jPanel);

    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReqTst;
    private javax.swing.JLabel imgLabTstReq;
    private javax.swing.JLabel lblEnt;
    private javax.swing.JLabel lblLabTyp;
    private javax.swing.JLabel lblLabTypReq;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblValue;
    private javax.swing.JTextField txtLabTyp;
    private javax.swing.JTextField txtMsg;
    // End of variables declaration//GEN-END:variables
}
