/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.VolunteerRole;

import code.Enterprise.Enterprise;
import code.SystemUserAccount.SystemUsers;
import code.ProcessQueue.OrderPlaceRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Rajvi
 */
public class ViewBeneficiaryJPanel extends javax.swing.JPanel {

    private JPanel jPanel;
    private SystemUsers userAccount;
    private Enterprise enterprise;
    private OrderPlaceRequest request;

    /**
     * Creates new form ViewPatientJPanel
     */

    ViewBeneficiaryJPanel(JPanel userProcessContainer, SystemUsers userAccount, Enterprise enterprise, OrderPlaceRequest workRequest) {
        initComponents();
        this.jPanel = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.request = workRequest;
        
        populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtHmPhnNo = new javax.swing.JTextField();
        lblPtntInfo = new javax.swing.JLabel();
        lblHmPhnNo = new javax.swing.JLabel();
        txtFrstNm = new javax.swing.JTextField();
        lblFrstNm = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddr = new javax.swing.JTextArea();
        lblAddr = new javax.swing.JLabel();
        lblPtntDtls = new javax.swing.JLabel();
        lblLstNm = new javax.swing.JLabel();
        txtLstNm = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        lblPtntMdclCndtn = new javax.swing.JLabel();
        lblPrscrptn = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPrscrptn = new javax.swing.JTextArea();
        txtPtntId = new javax.swing.JTextField();
        lblPtntId = new javax.swing.JLabel();
        txtPtntMdclCndtn = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        imgViewPtnt = new javax.swing.JLabel();

        setBackground(new java.awt.Color(253, 249, 232));

        txtHmPhnNo.setEditable(false);
        txtHmPhnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHmPhnNoActionPerformed(evt);
            }
        });

        lblPtntInfo.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblPtntInfo.setForeground(new java.awt.Color(204, 130, 43));
        lblPtntInfo.setText("BENEFICIARY INFORMATION");

        lblHmPhnNo.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblHmPhnNo.setForeground(new java.awt.Color(204, 130, 43));
        lblHmPhnNo.setText("Home phone No :");

        txtFrstNm.setEditable(false);

        lblFrstNm.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblFrstNm.setForeground(new java.awt.Color(204, 130, 43));
        lblFrstNm.setText("First Name :");

        jScrollPane1.setEnabled(false);

        txtAddr.setEditable(false);
        txtAddr.setColumns(20);
        txtAddr.setRows(5);
        jScrollPane1.setViewportView(txtAddr);

        lblAddr.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblAddr.setForeground(new java.awt.Color(204, 130, 43));
        lblAddr.setText("Address :");

        lblPtntDtls.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        lblPtntDtls.setForeground(new java.awt.Color(204, 130, 43));
        lblPtntDtls.setText("BENEFICIARY DETAILS");

        lblLstNm.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblLstNm.setForeground(new java.awt.Color(204, 130, 43));
        lblLstNm.setText("Last Name :");

        txtLstNm.setEditable(false);

        txtAge.setEditable(false);
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        lblAge.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblAge.setForeground(new java.awt.Color(204, 130, 43));
        lblAge.setText("Age :");

        lblPtntMdclCndtn.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblPtntMdclCndtn.setForeground(new java.awt.Color(204, 130, 43));
        lblPtntMdclCndtn.setText("Order Details:");

        lblPrscrptn.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblPrscrptn.setForeground(new java.awt.Color(204, 130, 43));
        lblPrscrptn.setText("List of Order Items");

        txtPrscrptn.setEditable(false);
        txtPrscrptn.setColumns(20);
        txtPrscrptn.setRows(5);
        jScrollPane2.setViewportView(txtPrscrptn);

        txtPtntId.setEditable(false);

        lblPtntId.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblPtntId.setForeground(new java.awt.Color(204, 130, 43));
        lblPtntId.setText("Beneficiary ID :");

        txtPtntMdclCndtn.setEditable(false);

        btnBack.setBackground(new java.awt.Color(204, 130, 43));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(253, 249, 232));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        imgViewPtnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BeneficiaryDetails.jpeg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnBack)
                .addGap(376, 376, 376)
                .addComponent(lblPtntDtls)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPtntId, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHmPhnNo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLstNm, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFrstNm, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPtntMdclCndtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(124, 124, 124))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(lblPtntInfo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFrstNm)
                                    .addComponent(lblLstNm)
                                    .addComponent(lblPtntId)
                                    .addComponent(lblHmPhnNo)
                                    .addComponent(lblAddr)
                                    .addComponent(lblAge)
                                    .addComponent(lblPtntMdclCndtn)
                                    .addComponent(lblPrscrptn))
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)))
                .addComponent(imgViewPtnt, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(lblPtntInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFrstNm)
                            .addComponent(txtFrstNm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLstNm)
                            .addComponent(txtLstNm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPtntId)
                            .addComponent(txtPtntId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHmPhnNo)
                            .addComponent(txtHmPhnNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(lblAddr))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lblAge))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPtntMdclCndtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPtntMdclCndtn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblPrscrptn)
                                .addGap(17, 17, 17)))
                        .addGap(71, 71, 71))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblPtntDtls)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imgViewPtnt, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtHmPhnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHmPhnNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHmPhnNoActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        jPanel.remove(this);
        CardLayout layout = (CardLayout)jPanel.getLayout();
        layout.previous(jPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel imgViewPtnt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAddr;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblFrstNm;
    private javax.swing.JLabel lblHmPhnNo;
    private javax.swing.JLabel lblLstNm;
    private javax.swing.JLabel lblPrscrptn;
    private javax.swing.JLabel lblPtntDtls;
    private javax.swing.JLabel lblPtntId;
    private javax.swing.JLabel lblPtntInfo;
    private javax.swing.JLabel lblPtntMdclCndtn;
    private javax.swing.JTextArea txtAddr;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFrstNm;
    private javax.swing.JTextField txtHmPhnNo;
    private javax.swing.JTextField txtLstNm;
    private javax.swing.JTextArea txtPrscrptn;
    private javax.swing.JTextField txtPtntId;
    private javax.swing.JTextField txtPtntMdclCndtn;
    // End of variables declaration//GEN-END:variables

    private void populate() {


        txtFrstNm.setText(request.getBeneficiary().getBenFirstName());
        txtLstNm.setText(request.getBeneficiary().getBenLastName());
        txtPtntId.setText(String.valueOf(request.getBeneficiary().getBenId()));
        txtAddr.setText(request.getBeneficiary().getAddress());
        txtHmPhnNo.setText(request.getBeneficiary().getContactNo());
        txtAge.setText(String.valueOf(request.getBeneficiary().getBenAge()));

        txtPtntMdclCndtn.setText(request.getVisitReason());
        txtPrscrptn.setText(request.getVolunteerNote());
    }
}
