/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FDASecretaryRole;

import code.Enterprise.Enterprise;
import code.Org.Organization;
import code.Org.OrgFDAManager;
import code.SystemUserAccount.SystemUsers;
import code.ProcessQueue.FDAApprovalRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jomraj
 */
public class SecretaryWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SecretaryWorkRequestJPanel
     */
    private JPanel jPanel;
    private Enterprise enterprise;
    private SystemUsers userAccount;
    private FDAApprovalRequest governmentFundRequest;

    public SecretaryWorkRequestJPanel(JPanel jPanel, SystemUsers userAccount, FDAApprovalRequest fundRequest, Enterprise enterprise) {
        initComponents();

        this.jPanel = jPanel;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.governmentFundRequest = fundRequest;
        restaurantIDText.setText(String.valueOf(governmentFundRequest.getRestaurantZipCode()));
        FDASecretaryProcessArea.setText(governmentFundRequest.getRestaurantName());
        ZipcodeText.setText(String.valueOf(governmentFundRequest.getRestaurantID()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        secretaryRequestProcessAreaLabel = new javax.swing.JLabel();
        sendRequestToManagerButton = new javax.swing.JButton();
        restaurantNameLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        FDASecretaryProcessArea = new javax.swing.JTextField();
        ZipcodeText = new javax.swing.JTextField();
        ZipCodeLabel = new javax.swing.JLabel();
        restaurantIDText = new javax.swing.JTextField();
        restaurantIDLabel = new javax.swing.JLabel();
        FDAMessageLabel = new javax.swing.JLabel();
        FDAMessageText = new javax.swing.JTextField();
        RestaurantDisapprovedButton = new javax.swing.JButton();
        imgSecReqProcessArea = new javax.swing.JLabel();

        setBackground(new java.awt.Color(253, 249, 232));

        secretaryRequestProcessAreaLabel.setFont(new java.awt.Font("YuGothic", 1, 24)); // NOI18N
        secretaryRequestProcessAreaLabel.setForeground(new java.awt.Color(204, 130, 43));
        secretaryRequestProcessAreaLabel.setText("Secretary Request Process area ");

        sendRequestToManagerButton.setBackground(new java.awt.Color(204, 130, 43));
        sendRequestToManagerButton.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        sendRequestToManagerButton.setText("Send Request to Manager ");
        sendRequestToManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendRequestToManagerButtonActionPerformed(evt);
            }
        });

        restaurantNameLabel.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        restaurantNameLabel.setForeground(new java.awt.Color(204, 130, 43));
        restaurantNameLabel.setText("Restaurant Name:");

        backButton.setBackground(new java.awt.Color(204, 130, 43));
        backButton.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        FDASecretaryProcessArea.setBackground(new java.awt.Color(204, 204, 204));
        FDASecretaryProcessArea.setEnabled(false);

        ZipcodeText.setBackground(new java.awt.Color(204, 204, 204));
        ZipcodeText.setEnabled(false);

        ZipCodeLabel.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        ZipCodeLabel.setForeground(new java.awt.Color(204, 130, 43));
        ZipCodeLabel.setText("Restaurant Zip Code");

        restaurantIDText.setBackground(new java.awt.Color(204, 204, 204));
        restaurantIDText.setEnabled(false);

        restaurantIDLabel.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        restaurantIDLabel.setForeground(new java.awt.Color(204, 130, 43));
        restaurantIDLabel.setText("Restaurant ID");

        FDAMessageLabel.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        FDAMessageLabel.setForeground(new java.awt.Color(204, 130, 43));
        FDAMessageLabel.setText("Message");

        FDAMessageText.setBackground(new java.awt.Color(204, 204, 204));
        FDAMessageText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FDAMessageTextActionPerformed(evt);
            }
        });

        RestaurantDisapprovedButton.setBackground(new java.awt.Color(204, 130, 43));
        RestaurantDisapprovedButton.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        RestaurantDisapprovedButton.setText("Restaurant Dissaproved");
        RestaurantDisapprovedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestaurantDisapprovedButtonActionPerformed(evt);
            }
        });

        imgSecReqProcessArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgSecReqProcessArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/16209033.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FDAMessageLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FDAMessageText, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(restaurantNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(restaurantIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FDASecretaryProcessArea, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(restaurantIDLabel)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ZipCodeLabel)
                                    .addGap(38, 38, 38)
                                    .addComponent(ZipcodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imgSecReqProcessArea)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(secretaryRequestProcessAreaLabel)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(sendRequestToManagerButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(RestaurantDisapprovedButton))))))
                .addContainerGap(371, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(secretaryRequestProcessAreaLabel)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(restaurantNameLabel)
                    .addComponent(FDASecretaryProcessArea, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(restaurantIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restaurantIDLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZipcodeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ZipCodeLabel))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FDAMessageText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FDAMessageLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendRequestToManagerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RestaurantDisapprovedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imgSecReqProcessArea, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sendRequestToManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendRequestToManagerButtonActionPerformed
        // TODO add your handling code here:

        String message = FDAMessageText.getText();
        if (message.equals("")) {
            JOptionPane.showMessageDialog(null, "Message is mandatory!");
            return;
        }
        else{
        governmentFundRequest.setProcessMessage(message);
        
        int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to proceed?");
            
         if (dialogResult == JOptionPane.YES_OPTION) {
        governmentFundRequest.setSndr(userAccount);
        governmentFundRequest.setProcessStatus("Sent to Manager");

        Organization org = null;
        for (Organization organization : enterprise.getOrgDir().getOrganizations()) {
            if (organization instanceof OrgFDAManager) {
                org = organization;
                break;
            }
        }
        if (org != null) {
            org.getProcessQueue().getProcesReq().add(governmentFundRequest);
            userAccount.getProcessQueue().getProcesReq().add(governmentFundRequest);
        }
        JOptionPane.showMessageDialog(null, "Request to Manager Successful!!!");
        FDAMessageText.setText("");
            RestaurantDisapprovedButton.setEnabled(false);
            sendRequestToManagerButton.setEnabled(false);
        }

        FDAMessageText.setText("");
        }
    }//GEN-LAST:event_sendRequestToManagerButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        jPanel.remove(this);
        Component[] componentArray = jPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SecretaryWorkAreaJPanel swjp = (SecretaryWorkAreaJPanel) component;
        swjp.ppltTbl();
        CardLayout layout = (CardLayout) jPanel.getLayout();
        layout.previous(jPanel);
    }//GEN-LAST:event_backButtonActionPerformed

    private void FDAMessageTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FDAMessageTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FDAMessageTextActionPerformed

    private void RestaurantDisapprovedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestaurantDisapprovedButtonActionPerformed
        String message = FDAMessageText.getText();
         if (message.equals("")) {
            JOptionPane.showMessageDialog(null, "Message is mandatory!");
            return;
        } else {
        governmentFundRequest.setProcessMessage(message);
        
         int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to proceed?");
            if (dialogResult == JOptionPane.YES_OPTION) {
                governmentFundRequest.setProcessStatus("Rejected");
                FDAMessageText.setText("");
            RestaurantDisapprovedButton.setEnabled(false);
            sendRequestToManagerButton.setEnabled(false);
            }
            FDAMessageText.setText("");
         }
    }//GEN-LAST:event_RestaurantDisapprovedButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FDAMessageLabel;
    private javax.swing.JTextField FDAMessageText;
    private javax.swing.JTextField FDASecretaryProcessArea;
    private javax.swing.JButton RestaurantDisapprovedButton;
    private javax.swing.JLabel ZipCodeLabel;
    private javax.swing.JTextField ZipcodeText;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel imgSecReqProcessArea;
    private javax.swing.JLabel restaurantIDLabel;
    private javax.swing.JTextField restaurantIDText;
    private javax.swing.JLabel restaurantNameLabel;
    private javax.swing.JLabel secretaryRequestProcessAreaLabel;
    private javax.swing.JButton sendRequestToManagerButton;
    // End of variables declaration//GEN-END:variables
}
