/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FoodInspectorRole;

import code.Enterprise.Enterprise;
import code.Org.Organization;
import code.Org.OrgSecretary;
import code.SystemUserAccount.SystemUsers;
import code.ProcessQueue.FDAApprovalRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jomraj
 */
public class InspectorWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    private JPanel jPanel;
    private Enterprise entrpz;
    private SystemUsers usrAcnt;
    private FDAApprovalRequest govtFndReq;
    private InspectorWorkAreaJPanel ofcrWrAreaJPanel;

    public InspectorWorkRequestJPanel(JPanel jPanel, SystemUsers userAccount, FDAApprovalRequest fundRequest, Enterprise enterprise) {
        initComponents();

        this.jPanel = jPanel;
        this.entrpz = enterprise;
        this.usrAcnt = userAccount;
        this.govtFndReq = fundRequest;
        restaurantIDText.setText(String.valueOf(govtFndReq.getRestaurantZipCode()));
        restaurantNameText.setText(govtFndReq.getRestaurantName());
        restaurantZipCodeText.setText(String.valueOf(govtFndReq.getRestaurantID()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        restaurantIDText = new javax.swing.JTextField();
        restaurantIDLabel = new javax.swing.JLabel();
        FoodInspectorMessageLabel = new javax.swing.JLabel();
        FoodInspectorMessageText = new javax.swing.JTextField();
        FoodInspectorProcessArea = new javax.swing.JLabel();
        sendToSecretaryButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        restaurantNameLabel = new javax.swing.JLabel();
        restaurantNameText = new javax.swing.JTextField();
        restaurantZipCodeText = new javax.swing.JTextField();
        ZipCodeLabel = new javax.swing.JLabel();
        rejectButton = new javax.swing.JButton();
        inspectorProcessRequestImage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(253, 249, 232));
        setForeground(new java.awt.Color(204, 130, 43));

        restaurantIDText.setBackground(new java.awt.Color(204, 204, 204));
        restaurantIDText.setEnabled(false);

        restaurantIDLabel.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        restaurantIDLabel.setForeground(new java.awt.Color(204, 130, 43));
        restaurantIDLabel.setText("Restaurant ID:");

        FoodInspectorMessageLabel.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        FoodInspectorMessageLabel.setForeground(new java.awt.Color(204, 130, 43));
        FoodInspectorMessageLabel.setText("Message");

        FoodInspectorMessageText.setBackground(new java.awt.Color(204, 204, 204));

        FoodInspectorProcessArea.setFont(new java.awt.Font("YuGothic", 1, 24)); // NOI18N
        FoodInspectorProcessArea.setForeground(new java.awt.Color(204, 130, 43));
        FoodInspectorProcessArea.setText("FOOD INSPECTOR PROCESSING AREA");

        sendToSecretaryButton.setBackground(new java.awt.Color(204, 130, 43));
        sendToSecretaryButton.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        sendToSecretaryButton.setText("Forward to Secretary");
        sendToSecretaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendToSecretaryButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(204, 130, 43));
        backButton.setFont(new java.awt.Font("YuGothic", 1, 11)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        restaurantNameLabel.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        restaurantNameLabel.setForeground(new java.awt.Color(204, 130, 43));
        restaurantNameLabel.setText("Restaurant Name:");

        restaurantNameText.setBackground(new java.awt.Color(204, 204, 204));
        restaurantNameText.setEnabled(false);

        restaurantZipCodeText.setBackground(new java.awt.Color(204, 204, 204));
        restaurantZipCodeText.setEnabled(false);

        ZipCodeLabel.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        ZipCodeLabel.setForeground(new java.awt.Color(204, 130, 43));
        ZipCodeLabel.setText("Zip Code:");

        rejectButton.setBackground(new java.awt.Color(204, 130, 43));
        rejectButton.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        rejectButton.setText("Reject");
        rejectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectButtonActionPerformed(evt);
            }
        });

        inspectorProcessRequestImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/16209033.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(backButton)
                .addGap(230, 230, 230)
                .addComponent(FoodInspectorProcessArea)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(409, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(sendToSecretaryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(rejectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(487, 487, 487))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(FoodInspectorMessageLabel)
                                    .addComponent(ZipCodeLabel))
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(restaurantZipCodeText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FoodInspectorMessageText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(restaurantIDLabel)
                                    .addComponent(restaurantNameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(restaurantIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(restaurantNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(552, 552, 552))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(inspectorProcessRequestImage, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FoodInspectorProcessArea)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(restaurantNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restaurantNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(restaurantIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restaurantIDLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(restaurantZipCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ZipCodeLabel))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FoodInspectorMessageText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FoodInspectorMessageLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rejectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendToSecretaryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(inspectorProcessRequestImage, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        jPanel.remove(this);
        Component[] componentArray = jPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        InspectorWorkAreaJPanel owjp = (InspectorWorkAreaJPanel) component;
        owjp.pplTbl();
        CardLayout layout = (CardLayout) jPanel.getLayout();
        layout.previous(jPanel);
    }//GEN-LAST:event_backButtonActionPerformed

    private void sendToSecretaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendToSecretaryButtonActionPerformed
        // TODO add your handling code here:

        String msg = FoodInspectorMessageText.getText();
        if (msg.equals("")) {
            JOptionPane.showMessageDialog(null, "Message is mandatory!");
            return;
        } else {
            govtFndReq.setProcessMessage(msg);

            int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to proceed?");

            if (dialogResult == JOptionPane.YES_OPTION) {

                govtFndReq.setSndr(usrAcnt);
                govtFndReq.setProcessStatus("Sent to Secretary");

                Organization org = null;
                for (Organization organization : entrpz.getOrgDir().getOrganizations()) {
                    if (organization instanceof OrgSecretary) {
                        org = organization;
                        break;
                    }
                }
                if (org != null) {
                    org.getProcessQueue().getProcesReq().add(govtFndReq);
                    usrAcnt.getProcessQueue().getProcesReq().add(govtFndReq);
                }
                JOptionPane.showMessageDialog(null, "Request to Secretary Successful!!!");
                FoodInspectorMessageText.setText("");
                rejectButton.setEnabled(false);
                sendToSecretaryButton.setEnabled(false);
            }
            FoodInspectorMessageText.setText("");
        }

    }//GEN-LAST:event_sendToSecretaryButtonActionPerformed

    private void rejectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectButtonActionPerformed
        String msg = FoodInspectorMessageText.getText();
        if (msg.equals("")) {
            JOptionPane.showMessageDialog(null, "Message is mandatory!");
            return;
        } else {
            govtFndReq.setProcessMessage(msg);
            int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to proceed?");

            if (dialogResult == JOptionPane.YES_OPTION) {
                govtFndReq.setProcessStatus("Rejected");
                FoodInspectorMessageText.setText("");
                rejectButton.setEnabled(false);
                sendToSecretaryButton.setEnabled(false);
            }

            FoodInspectorMessageText.setText("");
        }
    }//GEN-LAST:event_rejectButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FoodInspectorMessageLabel;
    private javax.swing.JTextField FoodInspectorMessageText;
    private javax.swing.JLabel FoodInspectorProcessArea;
    private javax.swing.JLabel ZipCodeLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel inspectorProcessRequestImage;
    private javax.swing.JButton rejectButton;
    private javax.swing.JLabel restaurantIDLabel;
    private javax.swing.JTextField restaurantIDText;
    private javax.swing.JLabel restaurantNameLabel;
    private javax.swing.JTextField restaurantNameText;
    private javax.swing.JTextField restaurantZipCodeText;
    private javax.swing.JButton sendToSecretaryButton;
    // End of variables declaration//GEN-END:variables
}
