/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdminRole;

import code.Enterprise.Enterprise;
import code.Org.Organization;
import code.Org.Organization.Type;
import code.Org.OrgDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author jomraj
 */
public class ManageOrganizationJPanel extends javax.swing.JPanel {

    private OrgDirectory dir;
    private JPanel jPanel;
    private Enterprise entrpz;

    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageOrganizationJPanel(JPanel userProcessContainer, OrgDirectory directory,
            Enterprise enterprise) {
        initComponents();
        this.jPanel = userProcessContainer;
        this.dir = directory;
        this.entrpz = enterprise;

        pplTbl();
        pplCmbx();
    }

    private void pplCmbx() {
        organizationComboBox.removeAllItems();
        // for (Type type : Organization.Type.values()){
        // if (!type.getValue().equals(Type.Admin.getValue()))
        // organizationJComboBox.addItem(type);
        // }
        for (Type orgType : entrpz.getAllOrgTypes()) {
            organizationComboBox.addItem(orgType);
        }
    }

    private void pplTbl() {
        DefaultTableModel model = (DefaultTableModel) organizationTable.getModel();

        model.setRowCount(0);

        for (Organization organization : dir.getOrganizations()) {
            Object[] row = new Object[2];
            row[0] = organization.getOrgID()-4;
            row[1] = organization;

            model.addRow(row);
        }
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        organizationTable.setRowSorter(sorter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        organizationTable = new javax.swing.JTable();
        addOrganisationButton = new javax.swing.JButton();
        organizationComboBox = new javax.swing.JComboBox();
        organisationTypeLabel = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        manageOrganisationHeaderLabel = new javax.swing.JLabel();
        deleteOrganisationButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(253, 249, 232));
        setToolTipText("");

        organizationTable.setBackground(new java.awt.Color(204, 204, 204));
        organizationTable.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        organizationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Organization Id", "Organization Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(organizationTable);
        if (organizationTable.getColumnModel().getColumnCount() > 0) {
            organizationTable.getColumnModel().getColumn(0).setResizable(false);
            organizationTable.getColumnModel().getColumn(1).setResizable(false);
        }

        addOrganisationButton.setBackground(new java.awt.Color(204, 130, 43));
        addOrganisationButton.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        addOrganisationButton.setText("Add Organization");
        addOrganisationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrganisationButtonActionPerformed(evt);
            }
        });

        organizationComboBox.setBackground(new java.awt.Color(204, 204, 204));
        organizationComboBox.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        organizationComboBox.setForeground(new java.awt.Color(204, 130, 43));
        organizationComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        organisationTypeLabel.setBackground(new java.awt.Color(204, 204, 204));
        organisationTypeLabel.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        organisationTypeLabel.setForeground(new java.awt.Color(204, 130, 43));
        organisationTypeLabel.setText("Organization Type ");

        backJButton.setBackground(new java.awt.Color(204, 130, 43));
        backJButton.setFont(new java.awt.Font("YuGothic", 1, 11)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        manageOrganisationHeaderLabel.setFont(new java.awt.Font("YuGothic", 1, 24)); // NOI18N
        manageOrganisationHeaderLabel.setForeground(new java.awt.Color(204, 130, 43));
        manageOrganisationHeaderLabel.setText("Manage Organizations");

        deleteOrganisationButton.setBackground(new java.awt.Color(204, 130, 43));
        deleteOrganisationButton.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        deleteOrganisationButton.setText("Delete");
        deleteOrganisationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteOrganisationButtonActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/transparent-icon-organization-5f0385efd8e2c9.9313673515940664158884.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(addOrganisationButton)
                        .addGap(34, 34, 34)
                        .addComponent(deleteOrganisationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(backJButton)
                        .addGap(196, 196, 196)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(organisationTypeLabel)
                                .addGap(56, 56, 56)
                                .addComponent(organizationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(manageOrganisationHeaderLabel)))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(manageOrganisationHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organizationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(organisationTypeLabel))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteOrganisationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addOrganisationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addOrganisationButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addJButtonActionPerformed

        Type type = (Type) organizationComboBox.getSelectedItem();
        // populateTable();
        ArrayList<String> orgName = new ArrayList<String>();
        DefaultTableModel model = (DefaultTableModel) organizationTable.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            orgName.add(model.getValueAt(i, 1).toString());
        }

        if (orgName.contains(type.getValue())) {
            JOptionPane.showMessageDialog(null, "Organization already exists!! ");
            return;
        } else {
            dir.createOrganization(type);
        }

        pplTbl();

    }// GEN-LAST:event_addJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backJButtonActionPerformed

        jPanel.remove(this);
        CardLayout layout = (CardLayout) jPanel.getLayout();
        layout.previous(jPanel);
    }// GEN-LAST:event_backJButtonActionPerformed

    private void deleteOrganisationButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeleteOrgActionPerformed
        // TODO add your handling code here:
        int selectedRow = organizationTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row first from the table to view details", "Warning!",
                    JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            Organization organization = (Organization) organizationTable.getValueAt(selectedRow, 1);

            entrpz.getOrgDir().getOrganizations().remove(organization);
            pplTbl();

        }

    }// GEN-LAST:event_btnDeleteOrgActionPerformed

    private void organizationJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_organizationJComboBoxActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_organizationJComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOrganisationButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton deleteOrganisationButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel manageOrganisationHeaderLabel;
    private javax.swing.JLabel organisationTypeLabel;
    private javax.swing.JComboBox organizationComboBox;
    private javax.swing.JTable organizationTable;
    // End of variables declaration//GEN-END:variables
}
