/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdminRole;

import code.EcoSystem;
import code.Enterprise.Enterprise;
import code.Networks.Networks;
import code.Org.OrgFoodInspector;
import code.Org.Organization;
import code.SystemUserAccount.SystemUsers;
import code.ProcessQueue.FDAApprovalRequest;
import code.ProcessQueue.ProcessRequest;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author shruti
 */
public class RequestReportJPanel extends javax.swing.JPanel {

    private JPanel jPanel;
    private Enterprise entrpz;
    private SystemUsers usrAc;
    private EcoSystem ecoSystem;

    /**
     * Creates new form RequestFundsJPanel
     */
    public RequestReportJPanel(JPanel jPanel, Enterprise enterprise, SystemUsers userAccount, EcoSystem ecoSystem) {
        initComponents();
        this.jPanel = jPanel;
        this.entrpz = enterprise;
        this.usrAc = userAccount;
        this.ecoSystem = ecoSystem;
        pplTbl();
    }

    public void pplTbl() {
        DefaultTableModel model = (DefaultTableModel) tblWrkReq.getModel();
        double totalFunds = 0;
        model.setRowCount(0);

        for (ProcessRequest request : usrAc.getProcessQueue().getProcesReq()) {

            if(request instanceof FDAApprovalRequest){
            Object[] row = new Object[4];
            row[0] = String.valueOf(((FDAApprovalRequest) request).getRestaurantName());
            row[1] = request.getRcvr();
            row[2] = request.getProcessStatus();
            row[3] = String.valueOf(((FDAApprovalRequest) request).getRestaurantZipCode());
            model.addRow(row);
            if (request.getProcessStatus().equalsIgnoreCase("Accepted")) {
                totalFunds += ((FDAApprovalRequest) request).getRestaurantZipCode();
            }
            }
        }

        txtTotFndRcvd.setText(String.valueOf(totalFunds));
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tblWrkReq.setRowSorter(sorter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTotFndRcvd = new javax.swing.JTextField();
        lblTotFundRcvd = new javax.swing.JLabel();
        lblRequestFund = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        txtLoc = new javax.swing.JTextField();
        lblPopulation = new javax.swing.JLabel();
        txtpop = new javax.swing.JTextField();
        lblAmt = new javax.swing.JLabel();
        txtAmt = new javax.swing.JTextField();
        btnSendFundReq = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWrkReq = new javax.swing.JTable();
        lblAllFndReq = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        imgReqFund = new javax.swing.JLabel();

        txtTotFndRcvd.setEditable(false);
        txtTotFndRcvd.setBackground(new java.awt.Color(204, 204, 204));
        txtTotFndRcvd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        lblTotFundRcvd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotFundRcvd.setText("Total Funds Received :");

        setBackground(new java.awt.Color(253, 249, 232));
        setLayout(null);

        lblRequestFund.setFont(new java.awt.Font("YuGothic", 1, 24)); // NOI18N
        lblRequestFund.setText("REQUEST REPORT");
        add(lblRequestFund);
        lblRequestFund.setBounds(260, 10, 228, 50);

        lblLocation.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        lblLocation.setForeground(new java.awt.Color(229, 227, 182));
        lblLocation.setText("Resaurant Name");
        add(lblLocation);
        lblLocation.setBounds(67, 69, 130, 22);

        txtLoc.setBackground(new java.awt.Color(204, 204, 204));
        txtLoc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocActionPerformed(evt);
            }
        });
        add(txtLoc);
        txtLoc.setBounds(260, 70, 141, 23);

        lblPopulation.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        lblPopulation.setForeground(new java.awt.Color(229, 227, 182));
        lblPopulation.setText("RestaurantID");
        add(lblPopulation);
        lblPopulation.setBounds(67, 107, 120, 22);

        txtpop.setBackground(new java.awt.Color(204, 204, 204));
        txtpop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpopActionPerformed(evt);
            }
        });
        add(txtpop);
        txtpop.setBounds(260, 100, 143, 23);

        lblAmt.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        lblAmt.setForeground(new java.awt.Color(229, 227, 182));
        lblAmt.setText("Zip Code");
        add(lblAmt);
        lblAmt.setBounds(67, 145, 130, 22);

        txtAmt.setBackground(new java.awt.Color(204, 204, 204));
        txtAmt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmtActionPerformed(evt);
            }
        });
        add(txtAmt);
        txtAmt.setBounds(260, 140, 143, 23);

        btnSendFundReq.setBackground(new java.awt.Color(255, 255, 255));
        btnSendFundReq.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        btnSendFundReq.setText("Send Request for Report");
        btnSendFundReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendFundReqActionPerformed(evt);
            }
        });
        add(btnSendFundReq);
        btnSendFundReq.setBounds(120, 180, 200, 30);

        tblWrkReq.setBackground(new java.awt.Color(204, 204, 204));
        tblWrkReq.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tblWrkReq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Restaurant Name", "ID", "Status", "Zip Code"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblWrkReq);

        add(jScrollPane1);
        jScrollPane1.setBounds(50, 320, 592, 97);

        lblAllFndReq.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        lblAllFndReq.setText("All Funds Requests");
        add(lblAllFndReq);
        lblAllFndReq.setBounds(270, 270, 150, 36);

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        btnBack.setText(" Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(30, 20, 90, 23);

        imgReqFund.setBackground(new java.awt.Color(253, 249, 232));
        imgReqFund.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        imgReqFund.setForeground(new java.awt.Color(229, 227, 182));
        imgReqFund.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/how-to-write-a-report.jpeg"))); // NOI18N
        add(imgReqFund);
        imgReqFund.setBounds(0, 0, 730, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocActionPerformed

    private void txtpopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpopActionPerformed

    private void txtAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmtActionPerformed

    private void btnSendFundReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendFundReqActionPerformed

        String location = txtLoc.getText().trim();
        String population = txtpop.getText();
        String amount = txtAmt.getText();
        if (location.equals("") || population.equals("") || amount.equals("")) {
            JOptionPane.showMessageDialog(null, "All fields are mandatory");
        } else {
            try {
                Integer.parseInt(population);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please type an Integer for Id");
                return;
            }
            try {
                Double.parseDouble(amount);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please type an numeric value for zip code");
                return;
            }
            FDAApprovalRequest governmentFundRequest = new FDAApprovalRequest(location, Integer.parseInt(population), Double.parseDouble(amount));
            governmentFundRequest.setSndr(usrAc);
            governmentFundRequest.setProcessStatus("Sent");

            Organization org = null;

            List<Networks> networks = ecoSystem.getNetworks();

            for (Networks network : networks) {

                List<Enterprise> enterprises = network.getEntDir().getEnterpriseList();
                for (Enterprise enterprise : enterprises) {
                    List<Organization> organizations = enterprise.getOrgDir().getOrganizations();
                    for (Organization organization : organizations) {
                        if (organization instanceof OrgFoodInspector) {
                            org = organization;
                            break;
                        }
                    }
                }
            }

            if (org != null) {

                org.getProcessQueue().getProcesReq().add(governmentFundRequest);
                usrAc.getProcessQueue().getProcesReq().add(governmentFundRequest);

            }
            pplTbl();
        }
    }//GEN-LAST:event_btnSendFundReqActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        jPanel.remove(this);
        CardLayout layout = (CardLayout) jPanel.getLayout();
        layout.previous(jPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSendFundReq;
    private javax.swing.JLabel imgReqFund;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAllFndReq;
    private javax.swing.JLabel lblAmt;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblPopulation;
    private javax.swing.JLabel lblRequestFund;
    private javax.swing.JLabel lblTotFundRcvd;
    private javax.swing.JTable tblWrkReq;
    private javax.swing.JTextField txtAmt;
    private javax.swing.JTextField txtLoc;
    private javax.swing.JTextField txtTotFndRcvd;
    private javax.swing.JTextField txtpop;
    // End of variables declaration//GEN-END:variables
}
