/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantManagerRole;


import code.ProcessQueue.OrderPlaceRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.RestaurantManagerRole.RestaurantManagerWorkJPanel;

/**
 *
 * @author Rajvi
 */
public class RestaurantWorkRequestJPanel extends javax.swing.JPanel {

    JPanel jPanel;
    OrderPlaceRequest ptTrWrReq;

    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public RestaurantWorkRequestJPanel(JPanel userProcessContainer, OrderPlaceRequest patientTreatmentWorkRequest) {
        initComponents();
        this.jPanel = userProcessContainer;
        this.ptTrWrReq = patientTreatmentWorkRequest;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitButton = new javax.swing.JButton();
        messageLabel = new javax.swing.JLabel();
        messageTeaxt = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        restaurantLabel = new javax.swing.JLabel();
        imageRestaurant = new javax.swing.JLabel();

        setBackground(new java.awt.Color(253, 249, 232));
        setLayout(null);

        submitButton.setBackground(new java.awt.Color(204, 130, 43));
        submitButton.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        submitButton.setForeground(java.awt.Color.white);
        submitButton.setText("Confirm Order");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        add(submitButton);
        submitButton.setBounds(260, 170, 140, 36);

        messageLabel.setBackground(new java.awt.Color(255, 255, 255));
        messageLabel.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        messageLabel.setForeground(new java.awt.Color(204, 130, 43));
        messageLabel.setText("Message");
        add(messageLabel);
        messageLabel.setBounds(170, 140, 60, 22);
        add(messageTeaxt);
        messageTeaxt.setBounds(250, 130, 160, 30);

        backButton.setBackground(new java.awt.Color(204, 130, 43));
        backButton.setFont(new java.awt.Font("YuGothic", 1, 11)); // NOI18N
        backButton.setText(" Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton);
        backButton.setBounds(30, 40, 75, 29);

        restaurantLabel.setFont(new java.awt.Font("YuGothic", 1, 24)); // NOI18N
        restaurantLabel.setForeground(new java.awt.Color(204, 130, 43));
        restaurantLabel.setText("Restaurant Work Request ");
        add(restaurantLabel);
        restaurantLabel.setBounds(180, 30, 310, 37);

        imageRestaurant.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        imageRestaurant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ordeerprocess.gif"))); // NOI18N
        add(imageRestaurant);
        imageRestaurant.setBounds(0, 0, 640, 470);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        jPanel.remove(this);
        Component[] componentArray = jPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        RestaurantManagerWorkJPanel dwjp = (RestaurantManagerWorkJPanel) component;
        dwjp.pplTbl();
        CardLayout layout = (CardLayout) jPanel.getLayout();
        layout.previous(jPanel);
    }//GEN-LAST:event_backButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        String bloodBankMessage = messageTeaxt.getText().trim();
        if (bloodBankMessage.equals("")) {
            JOptionPane.showMessageDialog(null, "Message is mandatory");
            return;
        } else {
            int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to proceed?");
            if (dialogResult == JOptionPane.YES_OPTION) {
                ptTrWrReq.setMsgFromRestaurant(bloodBankMessage);
                ptTrWrReq.setProcessStatus("Restaurant Request Completed");
                JOptionPane.showMessageDialog(null, "Status submitted successfully");
                messageTeaxt.setText("");
                submitButton.setEnabled(false);
            }

        }


    }//GEN-LAST:event_submitButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel imageRestaurant;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JTextField messageTeaxt;
    private javax.swing.JLabel restaurantLabel;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
