/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EBTFinanceRole;

import code.Enterprise.Enterprise;
import code.Org.OrgEBTFinance;
import code.SystemUserAccount.SystemUsers;
import code.ProcessQueue.cardRequest;
import code.ProcessQueue.ProcessRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author shruti
 */
public class EBTFinanceWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel jPanel;
    
    private SystemUsers usrAcnt;
    private OrgEBTFinance insrFincOrg;
    private Enterprise entrpz;

    /**
     * Creates new form InsuranceFinanceWorkAreaJPanel
     */
    public EBTFinanceWorkAreaJPanel(JPanel userProcessContainer, SystemUsers account, OrgEBTFinance insuranceFinanceOrganization, Enterprise enterprise) {
        initComponents();
        this.jPanel = userProcessContainer;
        this.usrAcnt = account;
        this.insrFincOrg = insuranceFinanceOrganization;
        this.entrpz = enterprise;
        pplTabl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInsFinance = new javax.swing.JTable();
        AssignToMeButton = new javax.swing.JButton();
        processRequestButton = new javax.swing.JButton();
        img = new javax.swing.JLabel();

        setBackground(new java.awt.Color(253, 249, 232));
        setForeground(new java.awt.Color(204, 130, 43));

        jLabel1.setFont(new java.awt.Font("YuGothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 130, 43));
        jLabel1.setText("Card Finance Work Area");

        tblInsFinance.setBackground(new java.awt.Color(204, 204, 204));
        tblInsFinance.setFont(new java.awt.Font("YuGothic", 1, 12)); // NOI18N
        tblInsFinance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Card Number", "Card Type", "Allowance", "Claim Amount", "Bill Amount", "Card Claim Status", "Requesting Food Bank ", "Finance Manager"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblInsFinance);

        AssignToMeButton.setBackground(new java.awt.Color(204, 130, 43));
        AssignToMeButton.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        AssignToMeButton.setForeground(new java.awt.Color(255, 255, 255));
        AssignToMeButton.setText("Assign To Me");
        AssignToMeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignToMeButtonActionPerformed(evt);
            }
        });

        processRequestButton.setBackground(new java.awt.Color(204, 130, 43));
        processRequestButton.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        processRequestButton.setForeground(new java.awt.Color(255, 255, 255));
        processRequestButton.setText("Process Request");
        processRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processRequestButtonActionPerformed(evt);
            }
        });

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/essential-technology-425x425.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AssignToMeButton)
                .addGap(74, 74, 74)
                .addComponent(processRequestButton)
                .addGap(417, 417, 417))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1085, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(406, 406, 406)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(processRequestButton)
                    .addComponent(AssignToMeButton))
                .addGap(18, 18, 18)
                .addComponent(img)
                .addContainerGap(185, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AssignToMeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignToMeButtonActionPerformed
        int selectedRow = tblInsFinance.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row first from the table to view details");
            return;
        } else {
            ProcessRequest req = (cardRequest) tblInsFinance.getValueAt(selectedRow, 0);
            if (req.getProcessStatus().equals("Sent To Finance Department")) {
                req.setRcvr(usrAcnt);
                req.setProcessStatus("Pending on " + req.getRcvr().getEmploye().getEmpName());
                pplTabl();
                JOptionPane.showMessageDialog(null, "Success !! Request is assigned to you");
            } else {
                JOptionPane.showMessageDialog(null, "Can't assign this work request, as the work request is in " + req.getProcessStatus() + " status", "Warning!", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_AssignToMeButtonActionPerformed

    private void processRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processRequestButtonActionPerformed
        // TODO add your handling code here:
        int selRow = tblInsFinance.getSelectedRow();
        if (selRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row first from the table to view details");
            return;
        } else {

            cardRequest insrWrReq = (cardRequest) tblInsFinance.getValueAt(selRow, 0);
            if (insrWrReq.getProcessStatus().equalsIgnoreCase("Sent To Finance Department")) {
                JOptionPane.showMessageDialog(null, "Assign the request first");
                return;
            }
            if (insrWrReq.getProcessStatus().equalsIgnoreCase("EBT Claim Approved")) {
                JOptionPane.showMessageDialog(null, "Request already Completed", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (!usrAcnt.equals(insrWrReq.getRcvr())) {
                JOptionPane.showMessageDialog(null, "Not Authorized", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (!usrAcnt.getEmploye().equals(insrWrReq.getRcvr().getEmploye())) {
                JOptionPane.showMessageDialog(null, "Request assigned to other Officer", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (insrWrReq.getProcessStatus().equals("EBT Claim Rejected")) {
                JOptionPane.showMessageDialog(null, "Cannot process a Rejected Request", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            } else {

                EBTFinanceRequest panel = new EBTFinanceRequest(jPanel, usrAcnt, insrWrReq, entrpz);
                jPanel.add("OfficerProcessWorkRequestJPanel", panel);
                CardLayout layout = (CardLayout) jPanel.getLayout();
                layout.next(jPanel);

            }
        }
    }//GEN-LAST:event_processRequestButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssignToMeButton;
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton processRequestButton;
    private javax.swing.JTable tblInsFinance;
    // End of variables declaration//GEN-END:variables

    public void pplTabl() {

        DefaultTableModel model = (DefaultTableModel) tblInsFinance.getModel();
        model.setRowCount(0);

        for (ProcessRequest workRequest : insrFincOrg.getProcessQueue().getProcesReq()) {
            cardRequest insrWkReq = ((cardRequest) workRequest);
            Object[] row = new Object[8];
            row[0] = insrWkReq;
            row[1] = insrWkReq.getTypeOfCard();
            row[2] = insrWkReq.getEbtMember().getEbt().getAllowance();
            row[3] = insrWkReq.getClmAmt();
            row[4] = insrWkReq.getBillingAmt();
            row[5] = insrWkReq.getProcessStatus();
            row[6] = insrWkReq.getInsuranceName();
            row[7] = insrWkReq.getRcvr() == null ? "" : insrWkReq.getRcvr().getEmploye().getEmpName();

            model.addRow(row);
        }
        
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tblInsFinance.setRowSorter(sorter);
    }

}
