/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NGODirectorRole;

import userinterface.NGODirectorRole.DirectorWorkAreaJPanel;
import code.ProcessQueue.FDAApprovalRequest;
import code.ProcessQueue.NGOFundRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shruti
 */
public class DirectorWorkRequestJPanel extends javax.swing.JPanel {

    private JPanel jPnl;
    private NGOFundRequest ngoFndReq;

    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public DirectorWorkRequestJPanel(JPanel jPanel, NGOFundRequest fundRequest) {
        initComponents();
        this.jPnl = jPanel;
        this.ngoFndReq = fundRequest;
        amountRequiredText.setText(String.valueOf(ngoFndReq.getAmountRequired()));
        hospitalNameText.setText(ngoFndReq.getAddressOfHospital());
        hospitalAddressText.setText(String.valueOf(ngoFndReq.getNameOfHospital()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        disburseAmountButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        rejectButton = new javax.swing.JButton();
        messageLabel = new javax.swing.JLabel();
        messageText = new javax.swing.JTextField();
        FoodBankNameLabel = new javax.swing.JLabel();
        hospitalNameText = new javax.swing.JTextField();
        hospitalAddressText = new javax.swing.JTextField();
        hospitalAddressLabel = new javax.swing.JLabel();
        amountRequiredText = new javax.swing.JTextField();
        AmountRequiredLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        img = new javax.swing.JLabel();

        setBackground(new java.awt.Color(253, 249, 232));

        disburseAmountButton.setBackground(new java.awt.Color(204, 130, 43));
        disburseAmountButton.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        disburseAmountButton.setText("Disburse Amount");
        disburseAmountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disburseAmountButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(204, 130, 43));
        backButton.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        rejectButton.setBackground(new java.awt.Color(204, 130, 43));
        rejectButton.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        rejectButton.setText("Reject");
        rejectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectButtonActionPerformed(evt);
            }
        });

        messageLabel.setFont(new java.awt.Font("YuGothic", 1, 12)); // NOI18N
        messageLabel.setForeground(new java.awt.Color(204, 130, 43));
        messageLabel.setText("Message:");

        FoodBankNameLabel.setFont(new java.awt.Font("YuGothic", 1, 12)); // NOI18N
        FoodBankNameLabel.setForeground(new java.awt.Color(204, 130, 43));
        FoodBankNameLabel.setText("Food Bank Name");

        hospitalNameText.setEnabled(false);

        hospitalAddressText.setEnabled(false);

        hospitalAddressLabel.setFont(new java.awt.Font("YuGothic", 1, 12)); // NOI18N
        hospitalAddressLabel.setForeground(new java.awt.Color(204, 130, 43));
        hospitalAddressLabel.setText("Food Bank Address");

        amountRequiredText.setEnabled(false);

        AmountRequiredLabel.setFont(new java.awt.Font("YuGothic", 1, 12)); // NOI18N
        AmountRequiredLabel.setForeground(new java.awt.Color(204, 130, 43));
        AmountRequiredLabel.setText("Amount Required:");

        jLabel1.setFont(new java.awt.Font("YuGothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 130, 43));
        jLabel1.setText("Director Work Area");

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/foodforthought.gif"))); // NOI18N
        img.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(381, 381, 381)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AmountRequiredLabel)
                                            .addComponent(FoodBankNameLabel)
                                            .addComponent(hospitalAddressLabel)
                                            .addComponent(messageLabel))
                                        .addGap(25, 25, 25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(messageText, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(hospitalAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(hospitalNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(amountRequiredText, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(disburseAmountButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rejectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FoodBankNameLabel)
                    .addComponent(hospitalNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountRequiredText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AmountRequiredLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hospitalAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hospitalAddressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messageLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disburseAmountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rejectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void disburseAmountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disburseAmountButtonActionPerformed
        disburseAmountButton.setEnabled(true);
        String message = messageText.getText();
        if (message.equals("")) {
            JOptionPane.showMessageDialog(null, "Message is mandatory!");
            return;
        }
        else
        {
        ngoFndReq.setProcessMessage(message);
         int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to proceed?");
         if (dialogResult == JOptionPane.YES_OPTION) {
        ngoFndReq.setProcessStatus("Accepted");
        JOptionPane.showMessageDialog(null, "Funds Disbursed Successfully!!!");
        disburseAmountButton.setEnabled(false);
        messageText.setText("");
        rejectButton.setEnabled(false);
        }
         messageText.setText("");
        }

    }//GEN-LAST:event_disburseAmountButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        jPnl.remove(this);
        Component[] componentArray = jPnl.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DirectorWorkAreaJPanel dwjp = (DirectorWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) jPnl.getLayout();
        layout.previous(jPnl);
    }//GEN-LAST:event_backButtonActionPerformed

    private void rejectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectButtonActionPerformed
        String message = messageText.getText();
        if (message.equals("")) {
            JOptionPane.showMessageDialog(null, "Message is mandatory!");
            return;
        } else {
        ngoFndReq.setProcessMessage(message);
        int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to proceed?");
            
            
            if (dialogResult == JOptionPane.YES_OPTION) {
        ngoFndReq.setProcessStatus("Rejected");
         messageText.setText("");
            rejectButton.setEnabled(false);
            disburseAmountButton.setEnabled(false);
        }
         messageText.setText("");   
        }
    }//GEN-LAST:event_rejectButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmountRequiredLabel;
    private javax.swing.JLabel FoodBankNameLabel;
    private javax.swing.JTextField amountRequiredText;
    private javax.swing.JButton backButton;
    private javax.swing.JButton disburseAmountButton;
    private javax.swing.JLabel hospitalAddressLabel;
    private javax.swing.JTextField hospitalAddressText;
    private javax.swing.JTextField hospitalNameText;
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JTextField messageText;
    private javax.swing.JButton rejectButton;
    // End of variables declaration//GEN-END:variables
}
